#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v3
# autospec commit: c1050fe
#
Name     : gnome-disk-utility
Version  : 45.1
Release  : 28
URL      : https://download.gnome.org/sources/gnome-disk-utility/45/gnome-disk-utility-45.1.tar.xz
Source0  : https://download.gnome.org/sources/gnome-disk-utility/45/gnome-disk-utility-45.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: gnome-disk-utility-bin = %{version}-%{release}
Requires: gnome-disk-utility-data = %{version}-%{release}
Requires: gnome-disk-utility-libexec = %{version}-%{release}
Requires: gnome-disk-utility-license = %{version}-%{release}
Requires: gnome-disk-utility-locales = %{version}-%{release}
Requires: gnome-disk-utility-man = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : pkgconfig(libcanberra-gtk3)
BuildRequires : pkgconfig(libhandy-1)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(libsecret-1)
BuildRequires : pkgconfig(pwquality)
BuildRequires : pkgconfig(udisks2)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: nodvd.patch

%description
# gnome-disk-utility
This gnome-disk-utility repository provides libraries and applications for
dealing with storage devices.

%package bin
Summary: bin components for the gnome-disk-utility package.
Group: Binaries
Requires: gnome-disk-utility-data = %{version}-%{release}
Requires: gnome-disk-utility-libexec = %{version}-%{release}
Requires: gnome-disk-utility-license = %{version}-%{release}

%description bin
bin components for the gnome-disk-utility package.


%package data
Summary: data components for the gnome-disk-utility package.
Group: Data

%description data
data components for the gnome-disk-utility package.


%package libexec
Summary: libexec components for the gnome-disk-utility package.
Group: Default
Requires: gnome-disk-utility-license = %{version}-%{release}

%description libexec
libexec components for the gnome-disk-utility package.


%package license
Summary: license components for the gnome-disk-utility package.
Group: Default

%description license
license components for the gnome-disk-utility package.


%package locales
Summary: locales components for the gnome-disk-utility package.
Group: Default

%description locales
locales components for the gnome-disk-utility package.


%package man
Summary: man components for the gnome-disk-utility package.
Group: Default

%description man
man components for the gnome-disk-utility package.


%prep
%setup -q -n gnome-disk-utility-45.1
cd %{_builddir}/gnome-disk-utility-45.1
%patch -P 1 -p1
pushd ..
cp -a gnome-disk-utility-45.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1703274285
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-disk-utility
cp %{_builddir}/gnome-disk-utility-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gnome-disk-utility/4cc77b90af91e615a64ae04893fdffa7939db84c || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gnome-disk-utility
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/gnome-disk-image-mounter
/V3/usr/bin/gnome-disks
/usr/bin/gnome-disk-image-mounter
/usr/bin/gnome-disks

%files data
%defattr(-,root,root,-)
/usr/share/applications/gnome-disk-image-mounter.desktop
/usr/share/applications/gnome-disk-image-writer.desktop
/usr/share/applications/org.gnome.DiskUtility.desktop
/usr/share/dbus-1/services/org.gnome.DiskUtility.service
/usr/share/glib-2.0/schemas/org.gnome.Disks.gschema.xml
/usr/share/icons/hicolor/scalable/apps/gnome-disks-state-standby-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.DiskUtility-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.DiskUtility.Devel.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.DiskUtility.svg
/usr/share/metainfo/org.gnome.DiskUtility.appdata.xml

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/gsd-disk-utility-notify
/usr/libexec/gsd-disk-utility-notify

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-disk-utility/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gnome-disk-image-mounter.1
/usr/share/man/man1/gnome-disks.1

%files locales -f gnome-disk-utility.lang
%defattr(-,root,root,-)

